---
- hosts: all
  become: true
  tags: role-test
  roles:
    - init_system

- hosts: all
  tags: collection-test
  vars:
    my_color_choice: 'blue'

  tasks:
    - name: "Verify {{ my_color_choice }} is a form of blue" 
      assert:
        that: my_color_choice is test_local_namespace.colors.blue


