---
- hosts: all
  become: true
  tags: test_role
  roles:
    - init_system

- hosts: all
  tags: test_collection
  vars:
    my_color_choice: 'blue'

  tasks:
    - name: "Verify {{ my_color_choice }} is a form of blue" 
      assert:
        that: my_color_choice is local.colors.blue


