---
roles:
  - name: init_system
    src: https://github.com/norayr-im/init-system.git
    version: main
    scm: git

collections:
  - name: git@github.com:norayr-im/ansible-collections.git
    type: git
    version: main
